package com.demo.soap.webservice.server_01;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-11-25T23:18:35.402+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "DemoFunctionInterfaceImplService", 
                  wsdlLocation = "http://192.168.1.16:9999/hello?wsdl",
                  targetNamespace = "http://server.webservice.soap.demo.com/")
public class DemoFunctionInterfaceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.webservice.soap.demo.com/", "DemoFunctionInterfaceImplService");
    public final static QName DemoFunctionInterfaceImplPort = new QName("http://server.webservice.soap.demo.com/", "DemoFunctionInterfaceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.16:9999/hello?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DemoFunctionInterfaceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.1.16:9999/hello?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DemoFunctionInterfaceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DemoFunctionInterfaceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoFunctionInterfaceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DemoFunctionInterfaceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DemoFunctionInterfaceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DemoFunctionInterfaceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns DemoFunctionInterface
     */
    @WebEndpoint(name = "DemoFunctionInterfaceImplPort")
    public DemoFunctionInterface getDemoFunctionInterfaceImplPort() {
        return super.getPort(DemoFunctionInterfaceImplPort, DemoFunctionInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DemoFunctionInterface
     */
    @WebEndpoint(name = "DemoFunctionInterfaceImplPort")
    public DemoFunctionInterface getDemoFunctionInterfaceImplPort(WebServiceFeature... features) {
        return super.getPort(DemoFunctionInterfaceImplPort, DemoFunctionInterface.class, features);
    }

}
