package com.demo.soap.webservice.server_01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-11-25T23:18:35.354+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://server_01.webservice.soap.demo.com/", name = "DemoFunctionInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface DemoFunctionInterface {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://server_01.webservice.soap.demo.com/", className = "com.demo.soap.webservice.server_01.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://server_01.webservice.soap.demo.com/", className = "com.demo.soap.webservice.server_01.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String sayHello(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
