package com.springcxf.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-11-28T09:04:25.761+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://api.springcxf.com/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @RequestWrapper(localName = "getUserInfo", targetNamespace = "http://api.springcxf.com/", className = "com.springcxf.api.GetUserInfo")
    @ResponseWrapper(localName = "getUserInfoResponse", targetNamespace = "http://api.springcxf.com/", className = "com.springcxf.api.GetUserInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.springcxf.api.User getUserInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
